version: "3.9"

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_PASSWORD=123456
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    environment:
      - MINIO_ROOT_USER=admin_gradute
      - MINIO_ROOT_PASSWORD=minio@password123
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc:RELEASE.2024-07-31T15-58-33Z
    depends_on:
      - minio
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /usr/bin/mc alias set minio http://minio:9000 admin minio@password123;
        /usr/bin/mc mb minio/wey-bucket;
        /usr/bin/mc anonymous set public minio/wey-bucket;
        exit 0;
